# Please keep this list alphabetized to simplify maintenance
Rails.application.config.rails_admin_highway_lookup_tables = [
  'BridgeAppraisalRatingType',
  'BridgeConditionRatingType',
  'BridgePostingType',
  'BridgeTollType',
  'ChannelConditionType',
  'CulvertConditionType',
  'DeckProtectionType',
  'DeckStructureType',
  'DesignConstructionType',
  'DesignLoadType',
  'FeatureSafetyType',
  'FunctionalClass',
  'HistoricalSignificanceType',
  'LoadRatingMethodType',
  'MaintenanceActivityType',
  'MaintenancePriorityType',
  'MaintenanceSection',
  'MembraneType',
  'OperationalStatusType',
  'ReferenceFeatureType',
  'Region',
  'RouteSigningPrefix',
  'ScourCriticalBridgeType',
  'ServiceLevelType',
  'ServiceOnType',
  'ServiceUnderType',
  'StrahnetDesignationType',
  'StructureAgentType',
  'StructureMaterialType',
  'StructureStatusType',
  'TrafficDirectionType',
  'WearingSurfaceType'
]

Rails.application.config.rails_admin_highway_models = ['HighwayStructure', 'BridgeLike', 'FieldReference', 'District']