Rails.application.config.rails_admin_highway_lookup_tables = [
  'BridgeAppraisalRatingType',
  'BridgeConditionRatingType',
  'ChannelConditionType',
  'DeckProtectionType',
  'DeckStructureType',
  'DesignConstructionType',
  'MembraneType',
  'OperationalStatusType',
  'ScourCriticalBridgeType',
  'StrahnetDesignationType',
  'StructureMaterialType',
  'WearingSurfaceType',
  'RouteSigningPrefix',
  'StructureStatusType',
  'Region',
  'MaintenanceSection',
  'ServiceOnType',
  'ServiceUnderType',
  'HistoricalSignificanceType',
  'BridgeTollType',
  'DesignLoadType',
  'LoadRatingMethodType',
  'BridgePostingType',
  'ReferenceFeatureType',
  'ServiceLevelType',
  'FunctionalClass',
  'TrafficDirectionType',
  'StructureAgentType'
]

Rails.application.config.rails_admin_highway_models = ['HighwayStructure', 'Bridge', 'FieldReference', 'District']