json.partial! 'api/v1/bridge_like_conditions/listing', bridge_like_condition: bridge_condition
json.deck_geometry_appraisal_rating_type_id bridge_condition.deck_geometry_appraisal_rating_type_id
json.underclearance_appraisal_rating_type_id bridge_condition.underclearance_appraisal_rating_type_id
