class AddAncillaryConditionTypes < ActiveRecord::DataMigration
  def up
    ancillary_condition_types = [
        {active: true, code: 'N', name: 'Not applicable', description: 'Used if structure is not an ancillary.'},
        {active: true, code: '9', name: 'Excellent', description: 'Newly completed construction.'},
        {active: true, code: '8', name: 'Very good', description: 'Near new construction. No damage or deterioration.'},
        {active: true, code: '7', name: 'Good', description: 'Minor problems. Shrinkage cracking in concrete and/or staining of surfaces. All connections are sound and hardware is tight. Coating system is functioning as designed with minor peeling or damage in isolated areas with no active corrosion.'},
        {active: true, code: '6', name: 'Satisfactory', description: 'Structural elements show minor deterioration. Hairline cracking in concrete greater than 0.012 inches wide with minor efflorescence, scaling, or pop-outs. Connections are functioning as intended. Coating system may be chalking, peeling, curling, or showing other early evidence of distress with isolated minor surface rust with no section loss.'},
        {active: true, code: '5', name: 'Fair', description: 'All primary structural elements are sound. Cracking in concrete less than 0.05 inches wide with moderate efflorescence, scaling, delamination, and/or spalls. Exposed rebar may have active corrosion with minor section loss. A few upper connection or splice fasteners may be loose and minor fabrication gaps may exist between mating flange surfaces. Coating system has evidence of distress with active corrosion and/or minor section loss to primary steel elements.'},
        {active: true, code: '4', name: 'Poor', description: 'Primary structural elements show advanced deterioration. Structural analysis is not yet warranted. Cracking in concrete greater than 0.05 inches wide with heavy efflorescence, scaling, delamination, and/or spalls. Exposed rebar has moderate section loss. Up to 25% of the fasteners are loose and mating flange surfaces may have moderate gaps not due to fabrication. Impact damage may be present. Coating has failed and moderate section loss to primary steel elements may be present. No cracking to steel elements exists. An increased inspection frequency is required. An Essential Repair Finding notification may be warranted.'},
        {active: true, code: '3', name: 'Serious', description: 'Deterioration or damage has seriously affected primary structural elements. Structural analysis may be warranted. Major repairs may be necessary. Concrete elements have significant cracking, spalling, and/or exposed rebar with advanced section loss. More than 25% of the fasteners are loose and/or some nuts and bolts may be missing, mating flange surfaces may have significant gaps not due to fabrication. Significant impact damage has occurred. Coating has failed with advanced section loss to primary steel members. Fatigue cracks in steel may be present. An increased inspection frequency and Essential Repair Finding notification is required.'},
        {active: true, code: '2', name: 'Critical', description: 'Advanced deterioration or damage to primary structural elements. Structural elements no longer functioning as designed. Structural analysis is warranted. Emergency repairs or shoring devices may be necessary for structure to remain in-service. Consideration should be given to removing or replacing the structure. Immediate notification and Essential Repair Finding is required.'},
        {active: true, code: '1', name: 'Imminent failure', description: 'Major deterioration or damage to primary structural elements. Structural stability has been compromised. Through-wall section loss in critical components, fatigue cracking, or damage that could cause structural failure is present. Traffic should be diverted from under the structure and it should immediately be removed from service. Immediate notification and Essential Repair Finding is required.'},
        {active: true, code: '0', name: 'Failed', description: 'One or more primary structural elements has failed. Structure is beyond repair and has been removed from service.'}
    ]

    ancillary_condition_types.each{|condition_type| AncillaryConditionType.create!(condition_type)}
  end
end
