class AddUpperConnectionTypes < ActiveRecord::DataMigration
  def up
    upper_connection_types = [
        {name: 'Double arm frame, vertical bolted connection, welded to vertical pole', code: '001', active: true},
        {name: 'Monotube, horizontal bolted connection, stiffened flanges', code: '002', active: true},
        {name: 'Double arm, horizontal bolted connection to simplex plate', code: '003', active: true},
        {name: 'Single face, single arm, double horizontal bolted connection to simplex plate (butterfly signs)', code: '004', active: true},
        {name: 'Double arm, square column, vertical bolted connection (butterfly signs)', code: '005', active: true},
        {name: 'Monotube, horizontal bolted connection, no gussets', code: '006', active: true},
        {name: 'Single face sign, single arm, cap-T horizontal bolted connection (butterfly signs)', code: '007', active: true},
        {name: 'Double face sign, single arm, cap-T horizontal bolted connection (butterfly signs)', code: '008', active: true},
        {name: 'Double arm (angle) truss, cap connection', code: '009', active: true},
        {name: 'Double face sign, single arm, double horizontal bolted connection to simplex plate (butterfly signs)', code: '010', active: true},
        {name: 'Three arm truss, U-bolt fitted connection on bearing plate', code: '011', active: true},
        {name: 'Double arm truss, bolted connection to top of pole and lower bearing plate', code: '012', active: true},
        {name: 'Double arm truss, bolted connection on bearing plates', code: '013', active: true},
        {name: 'Double arm, 3 finger collar connection', code: '014', active: true},
        {name: 'Double arm truss, U-bolt fitted connection on bearing plates on front of pole', code: '015', active: true},
        {name: 'Double arm (pipe) truss, cap connection', code: '016', active: true},
        {name: 'Double arm box truss, collar connection', code: '018', active: true},
        {name: 'Double arm box truss, cap connection (butterfly signs)', code: '019', active: true},
        {name: 'Double arm, 5 finger collar connection, or 5 finger U-bolt clamp connection', code: '020', active: true},
        {name: 'Double arm welded through vertical, vertical bolted cap connection', code: '021', active: true},
        {name: 'Double arm, 6 finger collar connection, or 6 finger U-bolt clamp connection', code: '024', active: true},
        {name: 'Double arm, welded collar to vertical, vertical bolted cap connection', code: '026', active: true},
        {name: 'Double arm frame, horizontal bolted connection to simplex plate with welded stiffener', code: '027', active: true},
        {name: 'Single arm, double collar connection, or double U-bolt connection', code: '028', active: true},
        {name: 'Double arm, bracket welded to vertical, vertical bolted connection', code: '030', active: true},
        {name: 'Double face sign, double arm, double horizontal bolted connection to simplex plate (butterfly signs)', code: '032', active: true},
        {name: 'Double arm, round column, vertical bolted cap connection (butterfly signs)', code: '033', active: true},
        {name: 'Double arm (angle) truss bolted cap connection to plates welded to vertical', code: '034', active: true},
        {name: 'Ornamental connection', code: '035', active: true},
        {name: 'Single face sign, double arm, double horizontal bolted connection to simplex plate (butterfly signs)', code: '036', active: true},
        {name: 'Double arm, double horizontal bolted connection to simplex plate with welded stiffeners (butterfly signs)', code: '038', active: true},
        {name: 'Monotube, vertical bolted connection, no gussets', code: '039', active: true},
        {name: 'Double arm truss, bolted connection to top of pole and lower bearing plate', code: '041', active: true},
        {name: 'Double arm, pipe fitted through vertical (butterfly signs)', code: '042', active: true},
        {name: 'Double arm, horizontal bolted connection to plate', code: '045', active: true},
        {name: 'Single arm, 3 finger collar connection', code: '046', active: true},
        {name: 'Single arm, horizontal bolted connection to simplex plate on front of pole', code: '047', active: true},
        {name: 'Double arm, horizontal bolted connection to stiffener reinforced plates', code: '048', active: true},
        {name: 'Double arm, horizontal bolted connection to simplex plate on front of pole (butterfly signs)', code: '049', active: true},
        {name: 'Double arm (angle) truss, top cap connection, truss bearing on bottom', code: '053', active: true},
        {name: 'Double arm, pipe fitted through vertical, welded', code: '058', active: true},
        {name: 'Double arm, horizontal bolted connection, stiffened flanges', code: '060', active: true},
        {name: 'Single arm, 4 bolt connection to simplex plate', code: '100', active: true},
        {name: 'Single arm, 6 bolt connection to simplex plate', code: '101', active: true},
        {name: 'Single arm, 4 bolt connection to simplex plate with welded stiffener', code: '102', active: true},
        {name: 'Single arm, 3 U-bolt connection', code: '103', active: true},
        {name: 'Single arm, box connection', code: '104', active: true},
        {name: 'Single arm, welded-clamped connection', code: '105', active: true},
        {name: 'Single arm, 3 bolt connection', code: '106', active: true},
        {name: 'Single arm, 4 bolt connection to wide simplex plate', code: '107', active: true},
        {name: 'Single arm, angled weld directly to column, with or without vertical pole on top', code: '108', active: true},
        {name: 'Quad arm, clamped connection', code: '109', active: true},
        {name: 'Double arm, clamped connection', code: '110', active: true},
        {name: 'Single arm, 4 bolt connection to simplex plate with welded bracket stiffener', code: '111', active: true},
        {name: 'Single arm, butterfly clamped connection', code: '112', active: true},
        {name: 'Single arm, circular welded connection', code: '113', active: true},
        {name: 'Double arm, 4 bolt connection to simplex plate', code: '114', active: true},
        {name: 'Double arm frame', code: '115', active: true},
        {name: 'Single arm, welded-clamped connection, with stiffeners', code: '117', active: true},
        {name: 'Unknown', code: '999', active: true}
    ]

    upper_connection_types.each{|uct| UpperConnectionType.create!(uct)}
  end
end